[tools]
python = "3"
"pipx:poetry" = "2"
act = "latest"
usage = "latest"
ruff = "latest"
pre-commit = "latest"
ubi = "latest"
# upx = "latest"  # Not available on Apple Silicon, install manually if desired

[tasks.installer]
description = "Run the ROLLER installer CLI"
run = "poetry run python -m roller_installer"

[tasks.deps]
description = "Install poetry dependencies for installer"
run = "poetry install --no-interaction --no-ansi"

[tasks.build]
description = "Build native ROLLER installer binary with optimizations"
run = "poetry run python scripts/build.py"
