[tools]
python = "3"
"pipx:poetry" = "2"
act = "latest"
usage = "latest"
ruff = "latest"
pre-commit = "latest"

[tasks.installer]
description = "Run the ROLLER installer CLI"
run = "poetry run python -m roller_installer"

[tasks.deps]
description = "Install poetry dependencies for installer"
run = "poetry install --no-interaction --no-ansi"

[tasks.build]
description = "Build native ROLLER installer binary"
run = "poetry run pyinstaller --onefile --name roller-installer --clean main.py"

[tasks.test-github-workflows]
description = "Test GitHub Actions locally with act"
run = "act"
