name: Build ROLLER Installer

on:
  push:
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.os-name }} Binary
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            os-name: Linux
            binary-suffix: ""
            ubi-suffix: ""
            artifact-name: roller-installer-linux-x64
            cache-key: linux
          - os: macos-latest
            os-name: macOS
            binary-suffix: ""
            ubi-suffix: ""
            artifact-name: roller-installer-macos-universal
            cache-key: macos
          - os: windows-2022
            os-name: Windows
            binary-suffix: ".exe"
            ubi-suffix: ".exe"
            artifact-name: roller-installer-windows-x64
            cache-key: windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          install: true
          cache: true
          experimental: true

      - name: Install Poetry dependencies
        run: |
          mise run deps

      - name: Build installer binary
        run: |
          mise run build

      - name: Test binary execution
        working-directory: dist
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            ./roller-installer.exe --help || echo "Binary test completed with exit code $?"
          else
            ./roller-installer --help || echo "Binary test completed with exit code $?"
          fi

      - name: Download ubi binary
        working-directory: dist
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            powershell -exec bypass -c "Invoke-WebRequest -URI 'https://raw.githubusercontent.com/houseabsolute/ubi/master/bootstrap/bootstrap-ubi.ps1' -UseBasicParsing | Invoke-Expression"
          else
            curl --silent --location https://raw.githubusercontent.com/houseabsolute/ubi/master/bootstrap/bootstrap-ubi.sh | TARGET=$(pwd) sh
          fi

      - name: Verify binaries
        working-directory: dist
        shell: bash
        run: |
          # List contents of dist directory
          ls -la

          # Verify both binaries exist
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            if [[ ! -f "roller-installer.exe" || ! -f "ubi.exe" ]]; then
              echo "Missing binaries!"
              exit 1
            fi
            echo "✓ Found roller-installer.exe and ubi.exe"
          else
            if [[ ! -f "roller-installer" || ! -f "ubi" ]]; then
              echo "Missing binaries!"
              exit 1
            fi
            echo "✓ Found roller-installer and ubi"
          fi

      - name: Upload artifact (folder)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: dist/
          retention-days: 30
          if-no-files-found: error
          compression-level: 6

  # Collect all artifacts for release
  collect-artifacts:
    name: Collect Release Artifacts
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create release ZIPs from artifacts
        run: |
          cd artifacts

          # Each artifact is already in a folder, create a ZIP from each
          for dir in */; do
            name="${dir%/}"
            echo "Creating ${name}.zip from ${dir} contents"
            cd "$dir"
            zip -r "../${name}.zip" *
            cd ..
            rm -rf "$dir"  # Remove the folder after zipping
          done

          # List created ZIPs
          echo "=== Created ZIPs ==="
          ls -la *.zip

      - name: Create checksums
        run: |
          cd artifacts
          # Create SHA256 checksums for all ZIP files
          for zip in *.zip; do
            sha256sum "$zip" >> checksums.txt
          done

          echo "=== Checksums ==="
          cat checksums.txt

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifacts/*.zip
            artifacts/checksums.txt
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Job to verify all builds completed successfully
  build-status:
    name: Build Status Check
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Check build results
        run: |
          echo "Build results:"
          echo "Linux: ${{ needs.build.result }}"

          if [[ "${{ needs.build.result }}" != "success" ]]; then
            echo "One or more builds failed"
            exit 1
          fi

          echo "All builds completed successfully!"

      - name: Build summary
        run: |
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Platform | Status | ZIP Contents |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|--------|--------------|" >> $GITHUB_STEP_SUMMARY
          echo "| Linux x64 | ✅ Success | roller-installer + ubi |" >> $GITHUB_STEP_SUMMARY
          echo "| macOS Universal | ✅ Success | roller-installer + ubi |" >> $GITHUB_STEP_SUMMARY
          echo "| Windows x64 | ✅ Success | roller-installer.exe + ubi.exe |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All installer ZIP packages built successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Each ZIP contains both the roller-installer binary and the ubi binary for self-contained distribution." >> $GITHUB_STEP_SUMMARY
