name: Build ROLLER Installer

on:
  push:
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.os-name }} Binary
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            os-name: Linux
            binary-suffix: ""
            ubi-suffix: ""
            artifact-name: roller-installer-linux-x64
            cache-key: linux
          - os: macos-latest
            os-name: macOS
            binary-suffix: ""
            ubi-suffix: ""
            artifact-name: roller-installer-macos-universal
            cache-key: macos
          - os: windows-2022
            os-name: Windows
            binary-suffix: ".exe"
            ubi-suffix: ".exe"
            artifact-name: roller-installer-windows-x64
            cache-key: windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          install: true
          cache: true
          experimental: true

      - name: Install Poetry dependencies
        run: |
          mise run deps

      - name: Build installer binary
        run: |
          mise run build

      - name: Test binary execution
        working-directory: dist
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            ./roller-installer.exe --help || echo "Binary test completed with exit code $?"
          else
            ./roller-installer --help || echo "Binary test completed with exit code $?"
          fi

      - name: Download ubi binary
        working-directory: dist
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            powershell -exec bypass -c "Invoke-WebRequest -URI 'https://raw.githubusercontent.com/houseabsolute/ubi/master/bootstrap/bootstrap-ubi.ps1' -UseBasicParsing | Invoke-Expression"
          else
            curl --silent --location https://raw.githubusercontent.com/houseabsolute/ubi/master/bootstrap/bootstrap-ubi.sh | TARGET=$(pwd) sh
          fi

      - name: Create release ZIP (Windows)
        if: runner.os == 'Windows'
        working-directory: dist
        shell: powershell
        run: |
          # Verify both binaries exist
          Get-ChildItem

          if (-not (Test-Path "roller-installer.exe") -or -not (Test-Path "ubi.exe")) {
            Write-Error "Missing binaries!"
            exit 1
          }

          # Create ZIP using PowerShell
          Compress-Archive -Path "roller-installer.exe", "ubi.exe" -DestinationPath "${{ matrix.artifact-name }}.zip"

          # Verify ZIP was created and show contents
          Get-ChildItem "${{ matrix.artifact-name }}.zip"

          # List ZIP contents for verification
          Add-Type -AssemblyName System.IO.Compression.FileSystem
          $zip = [System.IO.Compression.ZipFile]::OpenRead("$pwd\${{ matrix.artifact-name }}.zip")
          Write-Host "ZIP contents:"
          $zip.Entries | ForEach-Object { Write-Host "  - $($_.Name)" }
          $zip.Dispose()

      - name: Create release ZIP (Unix)
        if: runner.os != 'Windows'
        working-directory: dist
        shell: bash
        run: |
          # Verify both binaries exist
          ls -la

          if [[ ! -f "roller-installer" || ! -f "ubi" ]]; then
            echo "Missing binaries!"
            exit 1
          fi

          zip ${{ matrix.artifact-name }}.zip roller-installer ubi

          # Verify ZIP was created and list contents
          ls -la ${{ matrix.artifact-name }}.zip
          unzip -l ${{ matrix.artifact-name }}.zip

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: dist/${{ matrix.artifact-name }}.zip
          retention-days: 30
          if-no-files-found: error
          compression-level: 6

  # Collect all artifacts for release
  collect-artifacts:
    name: Collect Release Artifacts
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: binaries

      - name: List downloaded artifacts
        run: |
          find binaries -type f -exec ls -la {} \;

      - name: Create checksums
        run: |
          cd binaries
          find . -type f -name "*.zip" -exec sha256sum {} \; > checksums.txt
          cat checksums.txt

      - name: Upload checksums
        uses: actions/upload-artifact@v4
        with:
          name: checksums
          path: binaries/checksums.txt
          retention-days: 90

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            binaries/roller-installer-linux-x64/roller-installer-linux-x64.zip
            binaries/roller-installer-macos-universal/roller-installer-macos-universal.zip
            binaries/roller-installer-windows-x64/roller-installer-windows-x64.zip
            binaries/checksums.txt
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Job to verify all builds completed successfully
  build-status:
    name: Build Status Check
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Check build results
        run: |
          echo "Build results:"
          echo "Linux: ${{ needs.build.result }}"

          if [[ "${{ needs.build.result }}" != "success" ]]; then
            echo "One or more builds failed"
            exit 1
          fi

          echo "All builds completed successfully!"

      - name: Build summary
        run: |
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Platform | Status | ZIP Contents |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|--------|--------------|" >> $GITHUB_STEP_SUMMARY
          echo "| Linux x64 | ✅ Success | roller-installer + ubi |" >> $GITHUB_STEP_SUMMARY
          echo "| macOS Universal | ✅ Success | roller-installer + ubi |" >> $GITHUB_STEP_SUMMARY
          echo "| Windows x64 | ✅ Success | roller-installer.exe + ubi.exe |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All installer ZIP packages built successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Each ZIP contains both the roller-installer binary and the ubi binary for self-contained distribution." >> $GITHUB_STEP_SUMMARY
