name: Test ROLLER Installer

on:
  push:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-code:
    name: Test Installer Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          install: false
          cache: true
          experimental: true

      - name: Install dependencies
        run: |
          mise run install:ci
          mise run deps

      - name: Install lint dependencies
        run: |
          mise exec -- poetry install --with lint --no-interaction

      - name: Lint code
        run: |
          mise exec -- ruff check . || echo "Linting issues found"
          mise exec -- ruff format --check . || echo "Code formatting issues found"

      - name: Test CLI functionality
        run: |
          # Test basic CLI functionality
          mise run installer --help
